resolver: nightly-2017-02-03

packages:
- '.'

extra-deps:
- network-transport-inmemory-0.5.1  # snapshot 0.5.2 in lts-7.18
- distributed-process-0.7.3         # missing snapshot
- rematch-0.2.0.0
- distributed-process-systest-0.2.0
